export const SET_DAY = 'SET_DAY'
export const NEW_DAY = 'NEW_DAY'

export const FINISH_DAY = 'FINISH_DAY';
export const FINISH_DAY_SUCCESS = 'FINISH_DAY_SUCCESS';
export const FINISH_DAY_FAILURE = 'FINISH_DAY_FAILURE';

export const GET_FINISH_DAY_COUNT_SUCCESS = 'GET_FINISH_DAY_COUNT_SUCCESS';
export const GET_FINISH_DAY_COUNT_FAILURE = 'GET_FINISH_DAY_COUNT_FAILURE';
export const SET_FINISH_DAY_COUNT_SUCCESS = 'SET_FINISH_DAY_COUNT_SUCCESS';
export const SET_FINISH_DAY_COUNT_FAILURE = 'SET_FINISH_DAY_COUNT_FAILURE';

export const SELECT_DAY = 'SELECT_DAY';