export const SAVE_JOURNAL = 'SAVE_JOURNAL';
export const UPDATE_JOURNAL = 'UPDATE_JOURNAL';
export const DELETE_JOURNAL = 'DELETE_JOURNAL';

export const SAVE_AWARE_JOURNAL = 'SAVE_AWARE_JOURNAL';
export const UPDATE_AWARE_JOURNAL = 'UPDATE_AWARE_JOURNAL';
export const DELETE_AWARE_JOURNAL = 'DELETE_AWARE_JOURNAL';

export const SAVE_CBT_JOURNAL = 'SAVE_CBT_JOURNAL';
export const UPDATE__CBT_JOURNAL = 'UPDATE__CBT_JOURNAL';
export const DELETE_CBT_JOURNAL = 'DELETE_CBT_JOURNAL';