import { IDayType } from '../types';

export const singleDayContainingSelectedDay: IDayType = {
  '2021-01-01': {
    id: '',
    date: '2021-01-01',
    habitIds: [],
    cbtIds: [],
    awareIds: [],
    journalIds: [],
    habitCount: 0,
    habitPercentComplete: 0,
    finishedHabitCount: 0,
    mood: ['Great'],
    endOfDayNotes: [],
    finishDayClickedCount: 0,
  },
};

export const daysContainingSelectedDay: IDayType = {
  '2021-01-01': {
    id: '',
    date: '2021-01-01',
    habitIds: [],
    cbtIds: [],
    awareIds: [],
    journalIds: [],
    habitCount: 0,
    habitPercentComplete: 0,
    finishedHabitCount: 0,
    mood: ['Great'],
    endOfDayNotes: [],
    finishDayClickedCount: 0,
  },
  '2021-01-02': {
    id: '',
    date: '2021-01-02',
    habitIds: [],
    cbtIds: [],
    awareIds: [],
    journalIds: [],
    habitCount: 0,
    habitPercentComplete: 0,
    finishedHabitCount: 0,
    mood: ['Great'],
    endOfDayNotes: [],
    finishDayClickedCount: 0,
  },
  '2021-01-03': {
    id: '',
    date: '2021-01-03',
    habitIds: [],
    cbtIds: [],
    awareIds: [],
    journalIds: [],
    habitCount: 0,
    habitPercentComplete: 0,
    finishedHabitCount: 0,
    mood: ['Not Good'],
    endOfDayNotes: [],
    finishDayClickedCount: 0,
  },
  '2020-04-30': {
    id: '',
    date: '2020-04-30',
    habitIds: [],
    cbtIds: [],
    awareIds: [],
    journalIds: [],
    habitCount: 0,
    habitPercentComplete: 0,
    finishedHabitCount: 0,
    mood: ['Okay'],
    endOfDayNotes: [],
    finishDayClickedCount: 0,
  },
};
